POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "O meu blog",
    "author": "Coisito",
    "url": "www.blog.pt",
    "likes": 10,
    "userId": "6518aac06d3bd45dbc4cf510"
}
